### ISSUE TITLE
PHP Exception

### ISSUE THREAD

**Issue by joeworkman** [humhub/humhub-modules-updater#19]
Ever since updating to v2.1.7, I have been getting the following error in my Humhub instance and its actually been making my cron jobs file. 

```
PHP Warning 'yii\base\ErrorException' with message 'call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\updater\Events' not found'

in /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Event.php:312
```

**Comment by joeworkman** [comment]
Related: 

https://community.humhub.com/content/perma?id=216139
https://community.humhub.com/content/perma?id=216137

**Comment by luke-** [comment]
Hmm, I cannot reproduce this problem. Are you using the latest updater version? Can you reinstall the module?

**Comment by joeworkman** [comment]
I installed the module again and noticed that 1.5.2 got released today. It fixes some important things for me so I tried to update. :(

https://community.humhub.com/content/perma?id=218171

**Comment by luke-** [comment]
Did the problem occur again or is it fixed in the new version?

**Comment by joeworkman** [comment]
I have not seen the error yet. I will have a look at the logs again tomorrow and let you know.

**Comment by joeworkman** [comment]
It's still happening. And the cron job warning in my dashboard is back... 

```
yii\base\ErrorException: call_user_func() expects parameter 1 to be a valid callback, class 'humhub\modules\updater\Events' not found in /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Event.php:312 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError() #1 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func() #2 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger() #3 /home/joeworkman/websites/community.weavers.space/protected/humhub/commands/CronController.php(130): yii\base\Component->trigger() #4 /home/joeworkman/websites/community.weavers.space/protected/humhub/commands/CronController.php(55): humhub\commands\CronController->runDaily() #5 [internal function]: humhub\commands\CronController->actionRun() #6 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() #7 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams() #8 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction() #9 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction() #10 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction() #11 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction() #12 /home/joeworkman/websites/community.weavers.space/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest() #13 /home/joeworkman/websites/community.weavers.space/protected/yii(29): yii\base\Application->run() #14 {main}
```

**Comment by luke-** [comment]
Hmm, I cannot reproduce this problem...

Can you please execute:

```
cd protected
php yii module/list 
```

Do you have any other problems with your Humhub installation?
